#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ANVIL_PID_FILE="${PROJECT_DIR}/.anvil-pid"

# Anvil default account 0 private key
DEPLOYER_KEY="0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"

echo "=== ArenaForge Local Deploy ==="

# 1. Kill any existing anvil
if [ -f "$ANVIL_PID_FILE" ]; then
  OLD_PID=$(cat "$ANVIL_PID_FILE")
  kill "$OLD_PID" 2>/dev/null && echo "Killed previous anvil (PID: $OLD_PID)" || true
  rm -f "$ANVIL_PID_FILE"
  sleep 1
fi
# Also kill anything on port 8545
lsof -ti:8545 2>/dev/null | xargs kill 2>/dev/null || true
sleep 1

# 2. Start anvil
echo "Starting anvil..."
anvil --chain-id 31337 --balance 10000 > "${PROJECT_DIR}/.anvil.log" 2>&1 &
ANVIL_PID=$!
echo "$ANVIL_PID" > "$ANVIL_PID_FILE"
echo "Anvil started (PID: $ANVIL_PID)"

# 3. Wait for anvil to be ready
echo -n "Waiting for anvil"
for i in $(seq 1 30); do
  if curl -s http://127.0.0.1:8545 \
    -X POST \
    -H "Content-Type: application/json" \
    -d '{"jsonrpc":"2.0","method":"eth_chainId","params":[],"id":1}' \
    > /dev/null 2>&1; then
    echo " ready!"
    break
  fi
  echo -n "."
  sleep 0.5
done

# Verify anvil is actually running
if ! curl -s http://127.0.0.1:8545 -X POST -H "Content-Type: application/json" \
  -d '{"jsonrpc":"2.0","method":"eth_chainId","params":[],"id":1}' > /dev/null 2>&1; then
  echo " FAILED"
  echo "Anvil did not start. Check .anvil.log"
  exit 1
fi

# 4. Deploy contracts
echo ""
echo "Deploying contracts..."
cd "$PROJECT_DIR"

# Export private key for Deploy.s.sol's vm.envUint
export ARENA_AGENT_PRIVATE_KEY="$DEPLOYER_KEY"

forge script script/Deploy.s.sol \
  --broadcast \
  --rpc-url http://127.0.0.1:8545 \
  --private-key "$DEPLOYER_KEY" \
  2>&1

# 5. Parse deployed addresses from broadcast JSON
BROADCAST_FILE="${PROJECT_DIR}/broadcast/Deploy.s.sol/31337/run-latest.json"

if [ ! -f "$BROADCAST_FILE" ]; then
  echo "ERROR: Broadcast file not found at $BROADCAST_FILE"
  exit 1
fi

echo ""
echo "Parsing contract addresses..."

# Extract all 7 contract creation addresses in deploy order using a single python3 call
eval "$(python3 -c "
import json
data = json.load(open('$BROADCAST_FILE'))
creates = [tx for tx in data['transactions'] if tx.get('contractAddress')]
if len(creates) < 7:
    print(f'echo \"ERROR: Expected 7 contract deployments, found {len(creates)}\"; exit 1')
else:
    names = ['ESCROW_ADDR', 'REGISTRY_ADDR', 'CORE_ADDR', 'ORACLE_ADDR', 'STRATEGY_ADDR', 'AUCTION_ADDR', 'QUIZ_ADDR']
    for name, c in zip(names, creates):
        print(f'{name}=\"{c[\"contractAddress\"]}\"')
")"

# 6. Write .env
cat > "${PROJECT_DIR}/.env" <<EOF
# === LOCAL DEVELOPMENT (auto-generated by local-deploy.sh) ===
USE_LOCAL=true
USE_TESTNET=false

# RPC
MONAD_RPC_URL=http://127.0.0.1:8545
MONAD_TESTNET_RPC_URL=http://127.0.0.1:8545

# Deployer = Anvil account 0
ARENA_AGENT_PRIVATE_KEY=${DEPLOYER_KEY}

# Contract Addresses (deployed to local anvil)
ARENA_CORE_ADDRESS=${CORE_ADDR}
ESCROW_ADDRESS=${ESCROW_ADDR}
MATCH_REGISTRY_ADDRESS=${REGISTRY_ADDR}
ORACLE_DUEL_ADDRESS=${ORACLE_ADDR}
STRATEGY_ARENA_ADDRESS=${STRATEGY_ADDR}
AUCTION_WARS_ADDRESS=${AUCTION_ADDR}
QUIZ_BOWL_ADDRESS=${QUIZ_ADDR}

# Moltbook (disabled for local)
MOLTBOOK_API_URL=http://localhost:9999
MOLTBOOK_AGENT_HANDLE=ArenaForge-Local
MOLTBOOK_BEARER_TOKEN=local-dev-token

# Nad.fun (disabled for local)
NADFUN_API_URL=http://localhost:9998
EOF

# 7. Write frontend/.env
cat > "${PROJECT_DIR}/frontend/.env" <<EOF
# === FRONTEND LOCAL DEVELOPMENT (auto-generated by local-deploy.sh) ===
VITE_RPC_URL=http://127.0.0.1:8545
VITE_ARENA_CORE_ADDRESS=${CORE_ADDR}
VITE_MATCH_REGISTRY_ADDRESS=${REGISTRY_ADDR}
VITE_ESCROW_ADDRESS=${ESCROW_ADDR}
EOF

echo ""
echo "=== DEPLOYMENT COMPLETE ==="
echo ""
echo "ArenaCore:      $CORE_ADDR"
echo "WagerEscrow:    $ESCROW_ADDR"
echo "MatchRegistry:  $REGISTRY_ADDR"
echo "OracleDuel:     $ORACLE_ADDR"
echo "StrategyArena:  $STRATEGY_ADDR"
echo "AuctionWars:    $AUCTION_ADDR"
echo "QuizBowl:       $QUIZ_ADDR"
echo ""
echo ".env written successfully"
echo "frontend/.env written successfully"
echo "Anvil running (PID: $ANVIL_PID)"
echo ""
echo "Next steps:"
echo "  npm run test:e2e     # run E2E tests"
echo "  npm run agent:local  # start agent"
echo "  cd frontend && npm run dev  # start frontend"
echo "  npm run anvil:stop   # stop anvil"
